#!/bin/bash
docker run --name <%= @project %>-migration -it --rm -v /opt/<%= @project %>/log:/home/app/log -v /opt/<%= @project %>/assets:/home/app/public/assets -v /opt/<%= @project %>/tmp/cache:/home/app/tmp/cache --env-file ./.docker-env <%= @project %>/web:latest bundle exec rake db:migrate
